'use client'
import { useEffect, useMemo, useState } from 'react'
import { useAurora } from './AuroraContext'
import { BRAND, mailtoHref } from '@/config/site'
const ENQUIRIES=['Procurement','Distribution & Supply','System Design & Feasibility','Agriculture & Agro-Processing','Property & Estate Development','Fleet & Mobility','Investment & Partnership','Government & Development Finance','Media']
const PARAM:Record<string,string>={'system-design':'System Design & Feasibility','agriculture':'Agriculture & Agro-Processing','property-estate':'Property & Estate Development','distribution':'Distribution & Supply','fleet-mobility':'Fleet & Mobility'}
export default function BriefBuilder(){
 const [enquiry,setEnquiry]=useState(ENQUIRIES[0]); const [name,setName]=useState(''); const [organisation,setOrganisation]=useState(''); const [email,setEmail]=useState(''); const [site,setSite]=useState(''); const [notes,setNotes]=useState(''); const {surge}=useAurora()
 useEffect(()=>{const q=new URLSearchParams(window.location.search).get('enquiry'); if(q&&PARAM[q])setEnquiry(PARAM[q])},[])
 const showSite=['System Design & Feasibility','Agriculture & Agro-Processing','Property & Estate Development'].includes(enquiry)
 const body=useMemo(()=>[`Enquiry: ${enquiry}`,`Name: ${name||'(not given)'}`,`Organisation: ${organisation||'(not given)'}`,`Email: ${email||'(not given)'}`,showSite?`Site location and approximate size: ${site||'(not given)'}`:'','',notes||'(no further notes)'].filter(Boolean).join('\n'),[enquiry,name,organisation,email,site,notes,showSite])
 const field='w-full border border-[rgb(var(--surface-border)/.20)] bg-[rgb(var(--surface-raised)/.78)] px-4 py-3 text-[15px] text-[rgb(var(--surface-text))] placeholder:text-[rgb(var(--surface-muted)/.62)] transition-colors focus:border-[rgb(var(--gold-line))] focus:outline-none'
 const prefix=showSite?`[${enquiry}] `:''
 return <div className="grid gap-10 lg:grid-cols-[1.15fr_1fr] lg:gap-16"><div className="grid gap-5">
  <label className="grid gap-2"><span className="micro-label impact-kicker">Enquiry type</span><select className={field} value={enquiry} onChange={e=>setEnquiry(e.target.value)}>{ENQUIRIES.map(x=><option className="text-black" key={x}>{x}</option>)}</select></label>
  {[['Name',name,setName,'Your name'],['Organisation',organisation,setOrganisation,'Company or organisation'],['Email',email,setEmail,'you@company.com']].map(([label,value,setter,placeholder]:any)=><label className="grid gap-2" key={label}><span className="micro-label impact-kicker">{label}</span><input className={field} value={value} onChange={e=>setter(e.target.value)} placeholder={placeholder}/></label>)}
  {showSite&&<label className="grid gap-2"><span className="micro-label impact-kicker">Site location and approximate size <span className="normal-case opacity-70">(optional)</span></span><input className={field} value={site} onChange={e=>setSite(e.target.value)} placeholder="e.g. Lekki, Lagos — 40-unit estate"/></label>}
  <label className="grid gap-2"><span className="micro-label impact-kicker">Project details</span><textarea className={`${field} min-h-[130px] resize-y`} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Tell us what the site needs, the timeline, and what is already in place."/></label>
 </div><div className="lg:sticky lg:top-24 lg:self-start"><p className="micro-label impact-kicker">Enquiry preview</p><pre className="pad-card-tight mt-4 max-h-[360px] overflow-auto whitespace-pre-wrap border border-[rgb(var(--surface-border)/.14)] bg-[rgb(var(--surface-raised)/.72)] font-mono text-[12px] leading-[1.8] text-[rgb(var(--surface-muted))]">{body}</pre><a href={mailtoHref(`${prefix}Ano Energy enquiry`,body)} onClick={()=>surge(.7)} className="impact-button mt-6 inline-flex px-7 py-4 text-sm font-semibold">Open in your mail app →</a><p className="corporate-copy mt-4 max-w-[42ch] text-[13px] leading-6">This opens your mail client addressed to {BRAND.email}. Nothing is stored on this site.</p></div></div>
}
